/**
 * 契约类型统一出口：页面从 `~/api` 导入类型即可，无需直接引用生成目录。
 * 生成物 schema.d.ts 为契约镜像，禁止手改；此处仅做类型别名重导出。
 */
import type { components } from './generated/schema'

export type HealthResponse = components['schemas']['HealthResponse']
export type ZoneCreateRequest = components['schemas']['ZoneCreateRequest']
export type ZoneResponse = components['schemas']['ZoneResponse']
export type NodeRequest = components['schemas']['NodeRequest']
export type NodeResponse = components['schemas']['NodeResponse']
export type NodeStatusResponse = components['schemas']['NodeStatusResponse']
export type NodeStatusField = components['schemas']['NodeStatusField']
export type NodeCPUStatus = components['schemas']['NodeCPUStatus']
export type NodeMemoryStatus = components['schemas']['NodeMemoryStatus']
export type NodeDiskStatus = components['schemas']['NodeDiskStatus']
export type NodeNetStatus = components['schemas']['NodeNetStatus']
export type NodeNetIO = components['schemas']['NodeNetIO']
export type CreatePoolRequest = components['schemas']['CreatePoolRequest']
export type Pool = components['schemas']['Pool']
export type SetPoolNodesRequest = components['schemas']['SetPoolNodesRequest']
export type StorageTypeRequest = components['schemas']['StorageTypeRequest']
export type StorageType = components['schemas']['StorageType']
export type ImageRequest = components['schemas']['ImageRequest']
export type Image = components['schemas']['Image']
export type ImageZoneItem = components['schemas']['ImageZoneItem']
export type NodeImageStatus = components['schemas']['NodeImageStatus']
export type ImageDownloadRequest = components['schemas']['ImageDownloadRequest']
export type ImageOperation = components['schemas']['ImageOperation']
export type CreateVMRequest = components['schemas']['CreateVMRequest']
export type ImportVMRequest = components['schemas']['ImportVMRequest']
export type VMResponse = components['schemas']['VMResponse']
export type VMListItem = components['schemas']['VMListItem']
export type NodeWarning = components['schemas']['NodeWarning']
export type VMListResponse = components['schemas']['VMListResponse']
export type ResizeRequest = components['schemas']['ResizeRequest']
export type AcceptedResponse = components['schemas']['AcceptedResponse']
export type VMOperation = components['schemas']['VMOperation']
export type VMOperationsResponse = components['schemas']['VMOperationsResponse']
export type ErrorDetail = components['schemas']['ErrorDetail']
export type ErrorBody = components['schemas']['ErrorBody']
// 认证：契约中登录请求 schema 名为 LoginRequest（user/admin 身份域共用同一结构），
// 此处按管理员登录业务语义重导出为 AdminLoginRequest 别名，与 adminLogin 封装对应
export type AdminLoginRequest = components['schemas']['LoginRequest']
export type AdminLoginResponse = components['schemas']['AdminLoginResponse']
